Adiciona readme

diff --git a/ytt b/ytt
--- a/ytt
+++ b/ytt
@@ -9,12 +9,18 @@ if [[ $1 ]]; then
   yt_url="$1"
   yt_trans_file=transcricao.pt.srt
 else
-  echo 'erro: no url' >&2
+  echo 'error: need url' >&2
   exit 1
 fi
 
+# Check yt-dlp
+if ! type yt-dlp  >/dev/null; then
+  echo 'error: need yt-dlp' >&2
+  exit 1
+fi
+
+# Get transcript
 if [[ ! -f "$yt_trans_file" ]]; then
-  # Get transcript
   yt-dlp \
     --skip-download \
     --sub-format srt \
@@ -26,6 +32,7 @@ if [[ ! -f "$yt_trans_file" ]]; then
     "$yt_url"  
 fi
 
+# Get format transcript from
 yt_trans_txt=$(awk -f format.awk "$yt_trans_file")
 
 read -rp '
@@ -38,8 +45,15 @@ q) Quit
 Opção: ' opc
 
 case "$opc" in
-  p) echo "$yt_trans_txt"                   ;;
-  g) ./gui "$yt_trans_file"                 ;;
+  p) echo "$yt_trans_txt" ;;
+  g) 
+    if type yad  >/dev/null; then
+      ./gui "$yt_trans_file"
+    else
+      echo 'error: need yad to gui' >&2
+      exit 1
+    fi
+    ;;
   s) echo "$yt_trans_txt" > transcricao.txt ;;
-  q) exit 0                                 ;;
+  q) exit 0 ;;
 esac
